import { User } from "./user.model.js";
import { Base } from "./base.model.js";
import { Links } from "./links.model.js";

export interface Pull {
    url:                 string;
    id:                  number;
    node_id:             string;
    html_url:            string;
    diff_url:            string;
    patch_url:           string;
    issue_url:           string;
    number:              number;
    state:               string;
    locked:              boolean;
    title:               string;
    user:                User;
    body:                string;
    created_at:          Date;
    updated_at:          Date;
    closed_at:           null;
    merged_at:           null;
    merge_commit_sha:    string;
    assignee:            null;
    assignees:           any[];
    requested_reviewers: any[];
    requested_teams:     any[];
    labels:              any[];
    milestone:           null;
    draft:               boolean;
    commits_url:         string;
    review_comments_url: string;
    review_comment_url:  string;
    comments_url:        string;
    statuses_url:        string;
    head:                Base;
    base:                Base;
    _links:              Links;
    author_association:  string;
    auto_merge:          null;
    active_lock_reason:  null;
}